export type CountryRecord = {
  name: string
  code: string
  aliases?: string[]
}

/** Every ISO 3166-1 country and territory, with traveler-facing names. */
export const COUNTRIES: CountryRecord[] = [
  { name: "Afghanistan", code: "AF" },
  { name: "Åland Islands", code: "AX" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "American Samoa", code: "AS" },
  { name: "Andorra", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Anguilla", code: "AI" },
  { name: "Antarctica", code: "AQ" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Aruba", code: "AW" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bermuda", code: "BM" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO", aliases: ["Bolivia, Plurinational State of"] },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Bouvet Island", code: "BV" },
  { name: "Brazil", code: "BR" },
  { name: "British Indian Ocean Territory", code: "IO" },
  { name: "British Virgin Islands", code: "VG", aliases: ["Virgin Islands (British)"] },
  { name: "Brunei", code: "BN", aliases: ["Brunei Darussalam"] },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cabo Verde", code: "CV", aliases: ["Cape Verde"] },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Caribbean Netherlands", code: "BQ", aliases: ["Bonaire, Sint Eustatius and Saba"] },
  { name: "Cayman Islands", code: "KY" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN", aliases: ["PRC", "People's Republic of China"] },
  { name: "Christmas Island", code: "CX" },
  { name: "Cocos (Keeling) Islands", code: "CC" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Cook Islands", code: "CK" },
  { name: "Costa Rica", code: "CR" },
  { name: "Côte d'Ivoire", code: "CI", aliases: ["Cote d'Ivoire", "Ivory Coast"] },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Curaçao", code: "CW" },
  { name: "Cyprus", code: "CY" },
  { name: "Czechia", code: "CZ", aliases: ["Czech Republic"] },
  { name: "Democratic Republic of the Congo", code: "CD", aliases: ["Congo, Democratic Republic of the", "Congo-Kinshasa", "DR Congo", "DRC"] },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Eswatini", code: "SZ", aliases: ["Swaziland"] },
  { name: "Ethiopia", code: "ET" },
  { name: "Falkland Islands", code: "FK", aliases: ["Falkland Islands (Malvinas)"] },
  { name: "Faroe Islands", code: "FO" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "French Guiana", code: "GF" },
  { name: "French Polynesia", code: "PF" },
  { name: "French Southern Territories", code: "TF" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE", aliases: ["Deutschland"] },
  { name: "Ghana", code: "GH" },
  { name: "Gibraltar", code: "GI" },
  { name: "Greece", code: "GR" },
  { name: "Greenland", code: "GL" },
  { name: "Grenada", code: "GD" },
  { name: "Guadeloupe", code: "GP" },
  { name: "Guam", code: "GU" },
  { name: "Guatemala", code: "GT" },
  { name: "Guernsey", code: "GG" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Heard Island and McDonald Islands", code: "HM" },
  { name: "Honduras", code: "HN" },
  { name: "Hong Kong", code: "HK", aliases: ["HK", "Hong Kong SAR"] },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran", code: "IR", aliases: ["Iran, Islamic Republic of", "Persia"] },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Isle of Man", code: "IM" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jersey", code: "JE" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Laos", code: "LA", aliases: ["Lao People's Democratic Republic"] },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Macao", code: "MO", aliases: ["Macao SAR", "Macau"] },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Martinique", code: "MQ" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mayotte", code: "YT" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia", code: "FM", aliases: ["Micronesia, Federated States of"] },
  { name: "Moldova", code: "MD", aliases: ["Moldova, Republic of"] },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montenegro", code: "ME" },
  { name: "Montserrat", code: "MS" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM", aliases: ["Burma"] },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL", aliases: ["Holland", "Netherlands, Kingdom of the"] },
  { name: "New Caledonia", code: "NC" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Niue", code: "NU" },
  { name: "Norfolk Island", code: "NF" },
  { name: "North Korea", code: "KP", aliases: ["DPRK", "Democratic People's Republic of Korea", "Korea", "Korea, Democratic People's Republic of"] },
  { name: "North Macedonia", code: "MK", aliases: ["Macedonia"] },
  { name: "Northern Mariana Islands", code: "MP" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestine", code: "PS", aliases: ["Palestine, State of"] },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Pitcairn", code: "PN" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Puerto Rico", code: "PR" },
  { name: "Qatar", code: "QA" },
  { name: "Republic of the Congo", code: "CG", aliases: ["Congo", "Congo-Brazzaville"] },
  { name: "Réunion", code: "RE" },
  { name: "Romania", code: "RO" },
  { name: "Russia", code: "RU", aliases: ["Russian Federation"] },
  { name: "Rwanda", code: "RW" },
  { name: "Saint Barthélemy", code: "BL" },
  { name: "Saint Helena", code: "SH", aliases: ["Saint Helena, Ascension and Tristan da Cunha"] },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Martin", code: "MF", aliases: ["Saint Martin (French part)"] },
  { name: "Saint Pierre and Miquelon", code: "PM" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Sint Maarten", code: "SX", aliases: ["Sint Maarten (Dutch part)"] },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Georgia and the South Sandwich Islands", code: "GS" },
  { name: "South Korea", code: "KR", aliases: ["Korea", "Korea, Republic of", "Republic of Korea"] },
  { name: "South Sudan", code: "SS" },
  { name: "Spain", code: "ES", aliases: ["España"] },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Svalbard and Jan Mayen", code: "SJ" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH", aliases: ["Schweiz", "Suisse"] },
  { name: "Syria", code: "SY", aliases: ["Syrian Arab Republic"] },
  { name: "Taiwan", code: "TW", aliases: ["ROC", "Republic of China", "Taiwan, Province of China"] },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania", code: "TZ", aliases: ["Tanzania, United Republic of"] },
  { name: "Thailand", code: "TH" },
  { name: "Timor-Leste", code: "TL", aliases: ["East Timor"] },
  { name: "Togo", code: "TG" },
  { name: "Tokelau", code: "TK" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR", aliases: ["Turkiye", "Türkiye"] },
  { name: "Turkmenistan", code: "TM" },
  { name: "Turks and Caicos Islands", code: "TC" },
  { name: "Tuvalu", code: "TV" },
  { name: "U.S. Virgin Islands", code: "VI", aliases: ["Virgin Islands (U.S.)"] },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE", aliases: ["Emirates", "UAE"] },
  { name: "United Kingdom", code: "GB", aliases: ["Britain", "England", "Great Britain", "Northern Ireland", "Scotland", "UK", "United Kingdom of Great Britain and Northern Ireland", "Wales"] },
  { name: "United States", code: "US", aliases: ["America", "US", "USA", "United States of America"] },
  { name: "United States Minor Outlying Islands", code: "UM" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Vatican City", code: "VA", aliases: ["Holy See", "Vatican"] },
  { name: "Venezuela", code: "VE", aliases: ["Venezuela, Bolivarian Republic of"] },
  { name: "Vietnam", code: "VN", aliases: ["Viet Nam"] },
  { name: "Wallis and Futuna", code: "WF" },
  { name: "Western Sahara", code: "EH" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
]

function haystack(country: CountryRecord) {
  return [country.name, country.code, ...(country.aliases || [])].join(' ').toLowerCase()
}

export function findCountries(query: string, limit = COUNTRIES.length): CountryRecord[] {
  const q = query.trim().toLowerCase()
  if (!q) return COUNTRIES.slice()
  const scored = COUNTRIES.map(country => {
    const name = country.name.toLowerCase()
    const code = country.code.toLowerCase()
    const aliases = (country.aliases || []).map(item => item.toLowerCase())
    let score = 0
    if (name === q || code === q || aliases.includes(q)) score = 100
    else if (name.startsWith(q) || aliases.some(item => item.startsWith(q))) score = 80
    else if (haystack(country).includes(q)) score = 40
    return { country, score }
  }).filter(item => item.score > 0)
  scored.sort((a, b) => b.score - a.score || a.country.name.localeCompare(b.country.name, 'en'))
  return scored.slice(0, limit).map(item => item.country)
}

export function countryByName(name: string) {
  const q = name.trim().toLowerCase()
  return COUNTRIES.find(country =>
    country.name.toLowerCase() === q ||
    country.code.toLowerCase() === q ||
    (country.aliases || []).some(item => item.toLowerCase() === q),
  )
}

export function countryByCode(code: string) {
  return COUNTRIES.find(country => country.code.toLowerCase() === code.trim().toLowerCase())
}
